### ISSUE TITLE
Getting the number of geotiff bands.

### ISSUE THREAD

**Issue by santiquetzal** [IHCantabria/Leaflet.CanvasLayer.Field#14]
I'm reading a geotiff file using you library.
I follow the example showed in 'example_ScalarField_Geotiff.html', where the geotiff file has two bands and it works perfectly in my computer.

My tiff file have several bands too, but I don't know how many are until the file is downloaded from the server, so to make calls to `L.ScalarField.fromGeoTIFF(tiffData.response, <bandIndex>);` (one per band) I need to obtain the number of bands of the geotiff file before.

Do you know how can I obtain that value?

**Comment by VictorVelarde** [comment]
Hello @santiquetzal,

The plugin uses https://www.npmjs.com/package/geotiff to parse geotiff files. And the geotiff file needs to be available in the browser, so an ajax call is made. 

This mechanism does not allow a "selective download" of just one band / sublayer, it is just a common "download this resource from server" request (same as with a simple 'png').

To achieve that, so that you can download just the required band, you need some kind of server component, for example, an WCS Server. 

All in all the objective would be to download a geotiff from the server containing just the band you need.
