### ISSUE TITLE
GeoTIFF file is completely read when displaying a band

### ISSUE THREAD

**Issue by santiquetzal** [IHCantabria/Leaflet.CanvasLayer.Field#15]
Following the example `example_ScalarField_Geotiff.html`, to display bands of a geotiff file I need make a call with the number of the band to display to:
``` 
L.ScalarField.fromGeoTIFF(tiffData.response, <bandIndex>);
``` 
So, to show 3 bands I need to make 3 calls.

I was rewieving ScalarField.js, and I found that **for each call** to `fromGeoTIFF` the file is parsed by geotiff library, the image is read, and **all** rasters are read (this is an expensive operation, 5s in the browser with my file), but only the raster with the index received via `bandIndex` argument is used.

So... to display the 3 bands my browser works 15s when the job can be done in 5s.

```js
// Block taken from ScalarField.js
static fromGeoTIFF(data, bandIndex = 0) {

	let tiff = GeoTIFF.parse(data); // geotiff.js
	let image = tiff.getImage();
	let rasters = image.readRasters();
	...
	let zs = rasters[bandIndex]; 
	...
	let p = { ..., zs: zs};
	
	return new ScalarField(p);
```

I think you should read the rasters once independently of how many calls to fromGeoTIFF are done. 

Maybe moving the variable to another scope.  
Or receiving more than one bandIndex per call (so the user can gets all the bands with one call).

**Comment by VictorVelarde** [comment]
Hi,

`static fromGeoTIFF` is just a convenient method to simplify the creation of a ScalarField, considering a use case of just one relevant band inside the geotiff. It bundles parsing + scalarfield constructor.

I agree that it might be interesting to add a multi-band method, returning an array of `ScalarField`. I will add that as an enhancement for future releases.

In the meantime nothing stops you from separating both processes in your own app, so that you can reuse  `let tiff = GeoTIFF.parse(data);` and just iterate on its bands

PD. If you are succesful with that I will be glad to accept a pull-request

**Comment by VictorVelarde** [comment]
This has been improved with new `L.ScalarField.multipleFromGeoTIFF`method,
 for multiple bands (https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/pull/16)

It will be included in next release
