### ISSUE TITLE
Show continuous layers, beyond -180º to 180º (original: "Globe currents got an error")

### ISSUE THREAD

**Issue by wyj880220** [IHCantabria/Leaflet.CanvasLayer.Field#18]
Hello,I'm so sorry to bother you.I was use your plugin to show the globe current,i download the data from OSCAR,and i use arcpy tool to change file into arcgis ASCII format,but when i use the example to show the data,not all the map covered with currents,only one map layer(i don't know how to express it,if possible i will upload a picture to show you my puzzle) covered wih currents,is there someting wrong with me?

**Comment by VictorVelarde** [comment]
Hi @wyj880220,

You don't bother me at all... Thank you for using the plugin!
Our code can, of course, has some bugs, so it will be great if we can have a look at your problem, 

You can upload an image here or, even better, you could try to show your problem in a external, easy-to-debug, working enviroment, such as at codepen.io.

I have prepared two codepens for these situations:
* [VectorFieldAnim](https://codepen.io/VictorVelarde/pen/QvBeYV)
* [ScalarField](https://codepen.io/VictorVelarde/pen/ZKJWMb)

The only thing is up to you is to host your OSCAR ASCII grid datasets.

**Comment by wyj880220** [comment]
thank you for your reply,i upload the data to cloud storage，and it works well in my local server，but when i change the url of codepens，i got noting，so i built it in my own vps and use the example code，change the u and v url，which is [u_oscar](http://p07hdp87s.bkt.clouddn.com/u_oscar.asc?attname=) and [v_oscar](http://p07hdp87s.bkt.clouddn.com/v_oscar.asc?attname=),and my url is [ocean](http://45.32.31.91/ocean/ocean.html),you can see only one region have currents,but it is a global currents,i think the right imagination is like this  [leaflet-velocity](https://danwild.github.io/leaflet-velocity/)

**Comment by VictorVelarde** [comment]
Hi @wyj880220

I can't see any evident problem in your demo. These are the two screen captures I have made:

Your datasets @ QGIS
![oscar_qgis](https://user-images.githubusercontent.com/458196/33422824-31791ede-d5b7-11e7-9508-3e625d5712a6.png)

Your [ocean demo](http://45.32.31.91/ocean/ocean.html) using the plugin 
![oscar_plugin](https://user-images.githubusercontent.com/458196/33422842-3ed367ce-d5b7-11e7-9e20-0b203ee587e4.png)

Where is the missing region?

PD. I'm testing with latest Chrome & Firefox (could it be a browser issue?)
All in all, if you can use geotiff format instead of .asc the download time should be reduced

**Comment by wyj880220** [comment]
yes，you got it，maybe i use the word region is not correct，thank you，i think it is important,and i see a website [windy](https://www.windy.com/) is also use the leaflet,and it looks continuous and very beautiful.
