### ISSUE TITLE
How to generate/aquire input data

### ISSUE THREAD

**Issue by ri0t** [IHCantabria/Leaflet.CanvasLayer.Field#9]
I'm wondering how to get the examples to work with my own data.
I tried
* exports via zygrib where i gdal_translated the u/v bands - no data displayed at all (no js-errors as well)
* another export site (http://www.globalmarinenet.com/free-grib-file-downloads/) where i had some display but also weird maxed out values (14.141 m/s) so that those were extremely long lines and the other useful data was very tiny

I used
```
$ gdal_translate -of AAIGrid  -a_srs EPSG:4326 -b 1 gribdata.grb U.asc 
$ gdal_translate -of AAIGrid  -a_srs EPSG:4326 -b 2 gribdata.grb V.asc 

```
to generate the ascii grids. I also (obviously) had to pick out the correct bands via gdalinfo first.

Thanks in advance..
Edit: if needed, i can provide resulting ascii grid files, grib input etc

**Comment by VictorVelarde** [comment]
Hi @ri0t 

First of all, thank you very much for your interest in the plugin and the time you have dedicated to it. Let's see if I can help you!

It would be great if you could prepare a publicy available example. I have 2 codepens as templates for this kind of issues:
* VectorFieldAnim: https://codepen.io/VictorVelarde/pen/QvBeYV
* ScalarField: https://codepen.io/VictorVelarde/pen/ZKJWMb

Without that or at least an specific js-error it is difficult to diagnose what is happening. 

I would also try with just a small portion of those files, cause the plugin just can't handle big files, mainly due to browser limits.

Regards,
Víctor

**Comment by ri0t** [comment]
Hello @VictorVelarde - thanks for the quick reply. I have prepared the two examples:
1. https://riot.crew.c-base.org/vectorfield/docs/example1.html
2. https://riot.crew.c-base.org/vectorfield/docs/example2.html

I have included the original grib source files as well:
1. https://riot.crew.c-base.org/vectorfield/docs/data/gribdata.grb
2. https://riot.crew.c-base.org/vectorfield/docs/data/20170801_190250_.grb

hth!

**Comment by VictorVelarde** [comment]
Hi,

I have seen an issue with the input data at **example2**: y coordinate in ascii grid seems to be out of valid range [-90º, 90º].

This is a screen capture showing the wrong extent, after parsing both files in the plugin:
![example2_y_coordinate_error](https://user-images.githubusercontent.com/458196/28917172-089d60ee-7845-11e7-96bd-cab0e36b1f31.png)

I think that -a_srs in `gdal_translate` just overrides projection, but it doesn't reproject, try instead with `gdalwarp`.  You should reproject and check those files visually, e.g. with QGIS, then try again with the plugin. Their size is small, so I hope you will have no more problems after fixing that spatial reference.


Regarding to **example1**, I'm not sure, but maybe there is a similar projection problem. I couldn't check it properly, because the current version (1.2.1) is throwing too many warnings in log, and it 'freezes' my browser. I will release a new version 1.2.2 fixing that console.warn, but in the meantime you could just use previuous version (https://unpkg.com/leaflet-canvaslayer-field@1.2.0/dist/leaflet.canvaslayer.field.js)

Regards,

**Comment by ri0t** [comment]
Hmm. I tried various projection changes, but nothing delivered useable data. 
I got that datafile via the nice zygrib tool - it displays correctly there, yet not in qgis. Here's what gdalinfo tells about it:
```
Driver: GRIB/GRIdded Binary (.grb)
Files: 20170801_190250_.grb
       20170801_190250_.grb.aux.xml
Size is 83, 51
Coordinate System is:
GEOGCS["Coordinate System imported from GRIB file",
    DATUM["unknown",
        SPHEROID["Sphere",6371200,0]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]]
Origin = (-11.250000000000000,86.634000000000000)
Pixel Size = (0.500000000000000,-33.268000000000001)
Corner Coordinates:
Upper Left  ( -11.2500000,  86.6340000) ( 11d15' 0.00"W, 86d38' 2.40"N)
Lower Left  (     -11.250,   -1610.034) ( 11d15' 0.00"W,Invalid angle)
Upper Right (  30.2500000,  86.6340000) ( 30d15' 0.00"E, 86d38' 2.40"N)
Lower Right (      30.250,   -1610.034) ( 30d15' 0.00"E,Invalid angle)
Center      (       9.500,    -761.700) (  9d30' 0.00"E,Invalid angle)
Band 1 Block=83x1 Type=Float64, ColorInterp=Undefined
  Description = 10[m] HTGL (Specified height level above ground)
  Min=-7.910 Max=9.480 
  Minimum=-7.910, Maximum=9.480, Mean=0.722, StdDev=3.125
  Metadata:
    GRIB_COMMENT=u-component of wind [m/s]
    GRIB_ELEMENT=UGRD
```
... + lots and lots of bands for the timespans

The invalid angles somehow seem to be telling a tale here, but i do not fully understand it, yet.

**Comment by VictorVelarde** [comment]
Hi,

I have not used zygrib, but that *unkown DATUM* / 'invalid angle' and those *-1610.034 y values* are clearly the problem. Their unit seems to be just too big for decimal degrees. Maybe you can export the grib to another format before converting it asciigrid

I'm afraid this is not a plugin issue, but one related to previous data preparation, so I'm closing it.

Feel free to reopen it if the raster loads correctly in QGIS but not in the plugin.

**Comment by ri0t** [comment]
No, i am totally okay with closing this, as i agree. I am playing around with another (ecmwf) datasource now, that yields better results.

**Comment by VictorVelarde** [comment]
Great! If you have any other issue, just send us a message. 

And if you finally use the plugin in your project, we will be happy to receive an url or snapshot. That definitely helps to maintain the project.
